install:
	pip install conllu
	pip install numpy
	pip install datasets
	pip install transformers
	pip install sentencepiece
	conda install pytorch torchvision -c pytorch
	pip install seqeval

open:
	open "C:\Users\HP\Downloads\assign_2_cs689a.ipynb-20221105T090557Z-001\assign_2_cs689a.ipynb"
	
run:
	open  "C:\Users\HP\Downloads\22111059-Assignment2.ipynb"

